Journal list integration
FinHubSA/AK-Masterlist-Scraper pull request #3
Opened 2022-06-08 10:14 UTC by DanaeBouwer

**Integration of JSTOR journal list and fixing errors**

_Summary_
Integrated the journal_title_scraper into the masterlist_scraper to automatically pull the journals to scrape from JSTOR. Also fixed 2 errors encountered:
- element has 0 size
- connection interrupted

2022-06-08 12:25 UTC, wenkanglu requested changes
Looks good overall. Just a minor comment regarding a while loop. I would make the suggested change and update this pull request as practice.

2022-06-08 12:25 UTC, wenkanglu commented on masterlist_scraper.py
> +        while not os.path.isfile(old_name):
This loop is potentially infinite if the file is never successfully downloaded. Consider adding a maximum_duration constant that signifies the longest time we are willing to wait for a download before failing.

2022-06-13 10:10 UTC, wenkanglu approved these changes
Nice, easy fix.

2022-06-13 10:13 UTC, wenkanglu commented
To whoever is merging (Takunda/Danae), please select the "Squash and Merge" option when doing so.

2022-06-13 10:16 UTC, takundachirema approved these changes

2022-06-13 10:16 UTC, merged